FrontTestImaginamos/Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace FrontTestImaginamos.Models
{
    public class Login
    {
        public const string LOGIN_FALLIDO = "El usuario o la contraseña son incorrectos";

        [Required(ErrorMessage = "Ingrese su nombre de usuario")]
        [StringLength(50, ErrorMessage = "El nombre de usuario no debe superar los 50 caracteres")]
        public string Usuario { get; set; }
        
        [Display(Name = "Contraseña")]
        [Required(ErrorMessage = "Ingrese su contraseña")]
        [DataType(DataType.Password)]
        [StringLength(12, ErrorMessage = "La contraseña no debe superar los 12 caracteres")]
        public string Contrasena { get; set; }
    }
}

FrontTestImaginamos/Controllers/LoginController.cs
using FrontTestImaginamos.Models;
using System.Web.Mvc;

namespace FrontTestImaginamos.Controllers
{
    public class LoginController : Controller
    {
        private readonly BackWebServices.MainWebService webService = new BackWebServices.MainWebService();
        // GET: Login
        [HttpGet]
        public ActionResult Index()
        {
            if (Session["usuario"] != null)
            {
                return RedirectToAction("Index", "Producto");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Index(Login login)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var usuarioEncontrado = webService.Login(login.Usuario, login.Contrasena);

            if (usuarioEncontrado.Id < 1)
            {
                ModelState.AddModelError(string.Empty, Login.LOGIN_FALLIDO);
                return View();
            }

            Session["usuario"] = usuarioEncontrado;

            return RedirectToAction("Index", "Producto");
        }

        [HttpGet]
        public ActionResult Salir()
        {
            Session.Clear();
            Session.Abandon();
            return RedirectToAction("Index", "Login");
        }
    }
}

FrontTestImaginamos/Controllers/RegistroController.cs
using FrontTestImaginamos.Models;
using System;
using System.Web.Mvc;

namespace FrontTestImaginamos.Controllers
{
    public class RegistroController : Controller
    {
        private readonly BackWebServices.MainWebService webService = new BackWebServices.MainWebService();

        [HttpGet]
        // GET: Registro/Create
        public ActionResult Create()
        {
            if (Session["usuario"] != null)
            {
                return RedirectToAction("Index", "Producto");
            }

            return View();
        }

        // POST: Registro/Create
        [HttpPost]
        public ActionResult Create(Registro registro)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }

                webService.RegistrarUsuario(registro.Nombre,
                    registro.Documento,
                    registro.Email,
                    registro.NombreUsuario,
                    registro.Contrasena);

                ViewBag.RegistroExitoso = true;

                // TODO: Add insert logic here
            }
            catch(Exception ex)
            {
                ModelState.AddModelError(string.Empty, Registro.REGISTO_FALLIDO + " - " + ex.Message);
            }

            return View();
        }
    }
}

FrontTestImaginamos/Views/Login/Index.cshtml
@model FrontTestImaginamos.Models.Login

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contrasena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contrasena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contrasena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ingresar" class="btn btn-default" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Registrarse", "Create", "Registro")
            </div>
        </div>

    </div>
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>